### ISSUE TITLE
Support input[type=number]

### ISSUE THREAD

**Issue by supertassu** [GeoffSelby/tailwind-forms#2]
Number inputs currently have the default up/down buttons from the browser (tested with latest Chrome and Firefox):

![a](https://reeee.ee/RJqeKm.png)

**Comment by GeoffSelby** [comment]
Styling number inputs is impossible without significant JavaScript to to recreate the functionality. Not to mention browser support would likely be shot. You can read about styling them [here](http://form.guide/html5/html5-number-input-type.html).

I’ll leave this open for now while I do some more research.
